export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL';
export const DELETE_IMAGE_FAIL ='DELETE_IMAGE_FAIL';
export const DELETE_IMAGE_SUCCESS ='DELETE_IMAGE_SUCCESS';